import requests
import json

def test_ai_job_description():
    """Test AI job description generation"""
    
    # Test data
    test_jobs = [
        {
            "jobTitle": "React Developer",
            "company": "Trinity Technology",
            "jobType": "Full-time",
            "location": "Chennai, India"
        },
        {
            "jobTitle": "Python Developer", 
            "company": "Tech Solutions",
            "jobType": "Remote",
            "location": "Bangalore, India"
        },
        {
            "jobTitle": "Data Scientist",
            "company": "AI Corp",
            "jobType": "Full-time", 
            "location": "Hyderabad, India"
        }
    ]
    
    print("Testing AI Job Description Generation")
    print("=" * 50)
    
    for i, job in enumerate(test_jobs, 1):
        print(f"\nTest {i}: {job['jobTitle']}")
        print("-" * 30)
        
        try:
            response = requests.post(
                'http://localhost:5000/api/generate-job-description',
                json=job,
                timeout=20
            )
            
            if response.status_code == 200:
                result = response.json()
                print(f"Status: SUCCESS")
                print(f"Generated by: {result.get('generated_by', 'Unknown')}")
                print(f"\nDescription Preview:")
                print(result['description'][:200] + "...")
                print(f"\nRequirements Preview:")
                print(result['requirements'][:200] + "...")
            else:
                print(f"Status: FAILED ({response.status_code})")
                print(f"Error: {response.text}")
                
        except Exception as e:
            print(f"Status: ERROR - {e}")

if __name__ == '__main__':
    test_ai_job_description()